;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append-line
        evil-backward-char
        evil-forward-char
        evil-normal-state
        evil-paste-after
        ruby-electric-brace
        ruby-end-space
        ))

(setq mc/cmds-to-run-once
      '(
        control-meta-click
        delete-window
        evil-mouse-drag-region
        fix-for-evil
        ido-switch-buffer
        mouse-set-point
        mouse-set-region
        save-buffer-always
        smex
        widget-button-click
        ))
