;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all '(evil-append
                               evil-forward-paragraph
                               evil-backward-paragraph
                               evil-forward-section-begin
                               evil-backward-section-begin
                               paredit-backward-slurp-sexp
                               evil-paste-after
                               evil-copy-from-above
                               paredit-kill
                               paredit-forward-slurp-sexp
                               evil-emacs-state
                               keyboard-escape-quit
                               evil-find-char-to
                               evil-end-of-line
                               evil-change-line
                               ruby-end-space
                               evil-delete-line
                               paredit-backward-delete
                               evil-delete
                               evil-indent
                               mwheel-scroll
                               evil-append-line
                               evil-insert-line
                               evil-goto-line
                               evil-insert
                               evil-delete-char
                               evil-replace
                               evil-exit-emacs-state
                               mouse-drag-region
                               evil-normal-state
                               evil-change
                               evil-backward-word-begin
                               evil-force-normal-state
                               evil-forward-char
                               evil-visual-line
                               evil-backward-char
                               evil-visual-char
                               evil-forward-word-end
                               evil-exit-visual-state
                               evil-next-line
                               evil-previous-line))

(setq mc/cmds-to-run-once '(mouse-set-region
                            ido-switch-buffer
                            delete-window
                            smex
                            fix-for-evil
                            evil-mouse-drag-region
                            control-meta-click
                            mouse-set-point
                            save-buffer-always
                            widget-button-click))

                            
                               