(add-to-list 'load-path "~/.emacs.d")
(require 'sanity)
(require 'setup-paths)
(require 'setup-scratch-message)
(require 'compatibility)
(require 'setup-keys)
(require 'setup-hippie-expand)
(require 'setup-elpa-packages)
(require 'setup-elget-packages)
(require 'setup-mode-line)
(require 'setup-helpers)
(require 'sublimify)
(require 'emacsify)
(require 'movelines)
(require 'setup-backup)
(require 'setup-agda)
