(setq my-packages
      '(rainbow-delimiters
        coffee-mode
        paredit
        cider
        ac-nrepl
        find-file-in-project
        smex
        ido-ubiquitous
        undo-tree
        evil
        evil-surround
        evil-leader
        evil-exchange
        jell-theme
        enh-ruby-mode
        ruby-compilation
        scss-mode
        yaml-mode
        auto-complete
        markdown-mode
        rspec-mode
        jekyll-el
        ag
        bundler
        nyan-mode
        multiple-cursors
        smooth-scroll
        expand-region
        cl-lib
        magit
        git-timemachine
        web-mode
        puggle-utils
        dash
        s
        smartparens
        maps
        guide-key
        pivotal
        typed-clojure-mode
        elixir-mode
        idris-mode
        ace-jump-mode
        twittering-mode
        emacs-w3m
        bbdb
        gist
        haskell-mode
        erlang
        wgrep
        restclient
        feature-mode
        jinja2-mode
        matlab-mode
        rust-mode
        flymake-rust
        sass-mode))

(el-get 'sync my-packages)

(provide 'setup-packages)
