(require 'ruby-mode)
(require 'ruby-compilation)
(require 'rspec-mode)
(require 'rcodetools)
(rvm-activate-corresponding-ruby)
(rinari-launch)
(electric-pair-mode)
(setq enh-ruby-program "/Users/Jell/.rvm/rubies/ruby-1.9.3-p194/bin/ruby")
(setq rspec-use-rake-flag nil)
(setq rspec-use-opts-file-when-available nil)
(setq rspec-use-rvm t)
